import type { NextPage } from 'next'
import Head from 'next/head'
import DatePicker from 'react-datepicker';
import "react-datepicker/dist/react-datepicker.css";
import styles from '../styles/Home.module.css'

const Home: NextPage = ({ articles, error }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DatePicker/>
        {articles.data.map(articles => (
            <div id={articles.id}>
              <h3>Title: {articles.attributes.title}</h3>
              Description: {articles.attributes.body}
            </div>
        ))}
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

Home.getInitialProps = async ctx => {
  try {
    // Parses the JSON returned by a network request
    const parseJSON = resp => (resp.json ? resp.json() : resp);
    // Checks if a network request came back fine, and throws an error if not
    const checkStatus = resp => {
      if (resp.status >= 200 && resp.status < 300) {
        return resp;
      }

      return parseJSON(resp).then(resp => {
        throw resp;
      });
    };

    const headers = {
      'Content-Type': 'application/json',
    };

    const articles = await fetch('http://backend:1337/api/articles?populate=*', {
      method: 'GET',
      headers,
    })
        .then(checkStatus)
        .then(parseJSON);

    return { articles };
  } catch (error) {
    return { error };
  }
};


export default Home
